"""empty message

Revision ID: 132fffbbc1cb
Revises: b47456bc7db2
Create Date: 2023-07-07 16:18:42.186650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132fffbbc1cb'
down_revision = 'b47456bc7db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
