"""empty message

Revision ID: 430a91eccdcd
Revises: bd2cd0d8328a
Create Date: 2023-07-07 17:21:01.277328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430a91eccdcd'
down_revision = 'bd2cd0d8328a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('people_view', sa.Integer(), server_default='0', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('people_view')

    # ### end Alembic commands ###
